### ISSUE TITLE
Add description and contact info for bakeries

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/bakery-database#6]
Related to #5, we don't seem to have any of the "soft" metadata for bakeries. In [ADR 4](https://github.com/pangeo-forge/roadmap/blob/master/doc/adr/0004-use-yaml-file-for-bakery-database.md), we proposed stuff like

```yaml
  description: >
    Main bakery used for development and testing of Pangeo Forge.
    This bakery is operated by Lamont Doherty Earth Observatory of Columbia University.
  org_website: "http://ldeo.columbia.edu"
  region: aws.us-west2
  admins:
    - name: "Ryan Abernathey"
      orcid: "0000-0001-5999-4917"
      github: rabernat
      email: "rpa@ldeo.columbia.edu"
  targets:
```

We should fill this in for all bakeries.
